# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  publish = "dist/"
  command = "npm run generate --fail-on-page-error"


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
